/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TakeQuizRouteImport } from './routes/take-quiz'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedReviewQuizRouteImport } from './routes/_authed/review-quiz'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'

const TakeQuizRoute = TakeQuizRouteImport.update({
  id: '/take-quiz',
  path: '/take-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedReviewQuizRoute = AuthedReviewQuizRouteImport.update({
  id: '/review-quiz',
  path: '/review-quiz',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/take-quiz': typeof TakeQuizRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/review-quiz': typeof AuthedReviewQuizRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/take-quiz': typeof TakeQuizRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/review-quiz': typeof AuthedReviewQuizRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/take-quiz': typeof TakeQuizRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/review-quiz': typeof AuthedReviewQuizRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/take-quiz' | '/dashboard' | '/review-quiz'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/take-quiz' | '/dashboard' | '/review-quiz'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/take-quiz'
    | '/_authed/dashboard'
    | '/_authed/review-quiz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  TakeQuizRoute: typeof TakeQuizRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/take-quiz': {
      id: '/take-quiz'
      path: '/take-quiz'
      fullPath: '/take-quiz'
      preLoaderRoute: typeof TakeQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/review-quiz': {
      id: '/_authed/review-quiz'
      path: '/review-quiz'
      fullPath: '/review-quiz'
      preLoaderRoute: typeof AuthedReviewQuizRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedReviewQuizRoute: typeof AuthedReviewQuizRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedReviewQuizRoute: AuthedReviewQuizRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  TakeQuizRoute: TakeQuizRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
