/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TakeQuizRouteImport } from './routes/take-quiz'
import { Route as ReviewQuizRouteImport } from './routes/review-quiz'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const TakeQuizRoute = TakeQuizRouteImport.update({
  id: '/take-quiz',
  path: '/take-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewQuizRoute = ReviewQuizRouteImport.update({
  id: '/review-quiz',
  path: '/review-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/review-quiz': typeof ReviewQuizRoute
  '/take-quiz': typeof TakeQuizRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/review-quiz': typeof ReviewQuizRoute
  '/take-quiz': typeof TakeQuizRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/review-quiz': typeof ReviewQuizRoute
  '/take-quiz': typeof TakeQuizRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/review-quiz' | '/take-quiz'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/review-quiz' | '/take-quiz'
  id: '__root__' | '/' | '/dashboard' | '/review-quiz' | '/take-quiz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ReviewQuizRoute: typeof ReviewQuizRoute
  TakeQuizRoute: typeof TakeQuizRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/take-quiz': {
      id: '/take-quiz'
      path: '/take-quiz'
      fullPath: '/take-quiz'
      preLoaderRoute: typeof TakeQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review-quiz': {
      id: '/review-quiz'
      path: '/review-quiz'
      fullPath: '/review-quiz'
      preLoaderRoute: typeof ReviewQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ReviewQuizRoute: ReviewQuizRoute,
  TakeQuizRoute: TakeQuizRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
